add url schema for API v2 routing
haskell-CI/hackage-matrix-builder pull request #45
Opened 2017-10-03 16:52 UTC by Rizary

2017-10-03 17:56 UTC, hvr commented
@Rizary the good thing: the URL gets updated properly; the bad thing: if I enter the url, the page doesn't reflect the url state.

E.g.

http://localhost:8080/#/package/titlecase/0.1.0.3/ghc-7.4.2@1495446092

should point to a build-failure, instead it shows the latest index-state, i.e. http://localhost:8080/#/package/titlecase@1500274475; also, it doesn't open up the logs-window for the 01.0.3/ghc-7.4.2 cell.

2017-10-04 02:17 UTC, Rizary commented
@hvr it seems that the issue come from purescript-routing. I will check on that.

2017-10-10 09:23 UTC, Rizary commented
I notice that your IRC is still broken? i have sent you couple of chat.

2017-10-14 17:19 UTC, hvr requested changes
:tada: for removing the old  v1  api javascript code! :-)

2017-10-14 17:19 UTC, hvr commented on src-exe/Controller/Api.hs
> +  :<|> "v2" :> "users" :> "name"                 :> Capture "username" UserName :> Get '[JSON] UserPkgs
this results in `GET /api/v2/users/name/{username}`

we want instead:

 `GET /api/v2/users/{username}`

So change this to:

```
:<|> "v2" :> "users" :> Capture "username" UserName :> Get '[JSON] UserPkgs
```

2018-10-07 11:56 UTC, hvr commented
@Rizary most of this PR has been merged, except for https://github.com/haskell-CI/hackage-matrix-builder/pull/45/commits/437ac52d92e5fb93d4a0716ce696ad2381374145 for which I tried to cherry-pick into `master`, but it seems to be incomplete as I get the following compile failure:

```

[1/1 TypesDoNotUnify] /stuff3/work/GitHub/hackage-matrix-builder-3/src-ui.v2/src/Components/PageUser.purs:152:11

  152      st <- H.get
                 ^^^^^
  
  Could not match type
  
    ( packages :: Array (Tuple String Int)
    , user :: RemoteData Error (Array String)
    , withReports :: Boolean
    , initUser :: String
    )
  
  with type
  
    ( packages :: t2
    , userPkg :: t3
    , initUser :: String
    | t4
    )
  
  while trying to match type { initUser :: String
                             , user :: RemoteData Error (Array String)
                             , packages :: Array (Tuple String Int)
                             , withReports :: Boolean
                             }
    with type { initUser :: String
              , packages :: t2
              , userPkg :: t3
              | t4
              }

```

2019-01-09 10:33 UTC, closed without merging

2019-01-09 10:34 UTC, Rizary commented
Closed as we move to Reflex-Dom.